---

- name: Clone Git Repository Locally
  hosts: localhost
  connection: local

  vars_files:
    - vars.yml

  tasks:

    - name: Delete local extension files
      file:
        path: "integration-module-extensions"
        state: absent

    - name: Clone repository im-extensions
      git:
        repo: "{{im_ext_repo}}"
        dest: "{{ playbook_dir }}/integration-module-extensions"
        version: "{{im_ext_branch}}"
        update: true

...
