---

- name: Create a directory if it does not exist
  file:
    path: /home/{{user}}/proxy/certs
    state: directory
    mode: '0750'
    recurse: true

- name: Create private keys
  command: "openssl ecparam -name secp384r1 -genkey -noout \
           -out /home/{{user}}/proxy/certs/{{item.name}}.key"
  loop: "{{vms}}"

- name: Save selfsigned certs
  command: "openssl req -new -x509 -key /home/{{user}}/proxy/certs/{{item.name}}.key \
           -out /home/{{user}}/proxy/certs/{{item.name}}.crt  -days 360 \
           -subj '/CN={{item.name}}/O=DTU/OU=AIT/C=DK'"
  loop: "{{vms}}"

...
