---

- name: Install firewalld
  dnf:
    name: firewalld-1.2.1
    state: present

- name: Enables firewalld
  systemd:
    state: started
    enabled: true
    name: firewalld

- name: Allows https
  ansible.posix.firewalld:
    immediate: true
    port: "{{item}}"
    permanent: true
    state: enabled
    zone: public
  loop:
    - 443/tcp

- name: Redirect port 443 to 8443 with Rich Rule
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
    zone: public
    permanent: true
    immediate: true
    state: enabled

- name: Restart firewalld
  systemd:
    state: restarted
    daemon_reload: true
    name: firewalld

...
